// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package trips

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"

	"github.com/brady1408/auto-transport-logistics/internal/handler/components"
	"github.com/brady1408/auto-transport-logistics/internal/models"
)

func ListPage(pg components.PageContext, result models.TripListResult, filter models.TripFilter) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Page Header --> <div class=\"flex items-end justify-between mb-6\"><div><nav class=\"flex items-center gap-2 text-xs text-outline mb-2 font-medium tracking-wide uppercase\"><span>Dispatch</span> <span class=\"material-symbols-outlined text-[14px]\">chevron_right</span> <span class=\"text-secondary\">Trips</span></nav><div class=\"flex items-center gap-4\"><h1 class=\"text-3xl font-extrabold tracking-tight text-on-surface\" style=\"font-family: 'Manrope', sans-serif;\">Trips / Loads</h1><span class=\"px-3 py-1 rounded-full bg-primary-container text-white text-xs font-bold tracking-tight\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", result.TotalCount))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/trips/list.templ`, Line: 22, Col: 145}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div></div><a href=\"/dispatch/trips/new\" class=\"flex items-center gap-2 bg-primary-container text-white px-5 py-2.5 rounded-xl font-bold text-sm no-underline hover:opacity-90 active:scale-95 transition-all shadow-lg shadow-primary-container/10\"><span class=\"material-symbols-outlined text-[18px]\">add</span> New Trip</a></div><!-- Filter Bar --> <div class=\"bg-surface-container-lowest p-5 rounded-xl shadow-sm border border-outline-variant/10 mb-6\"><div class=\"flex flex-wrap items-end gap-4\"><div class=\"flex-1 min-w-[240px]\"><label for=\"search\" class=\"text-[10px] font-bold text-outline uppercase tracking-widest block mb-1.5\">Quick Search</label><div class=\"relative\"><span class=\"material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-[20px]\">search</span> <input type=\"text\" id=\"search\" name=\"search\" class=\"w-full bg-surface-container-low border-none rounded-lg pl-10 pr-4 py-2.5 text-sm focus:ring-2 focus:ring-primary-container/20 transition-colors\" placeholder=\"Trip #, truck, or driver...\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(filter.Search)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/trips/list.templ`, Line: 41, Col: 28}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-get=\"/dispatch/trips\" hx-trigger=\"keyup changed delay:300ms\" hx-target=\"#trip-table\" hx-include=\".filter-section [name]\" hx-push-url=\"true\" style=\"font-family: 'Inter', sans-serif;\"></div></div><div class=\"min-w-[140px]\"><label for=\"active\" class=\"text-[10px] font-bold text-outline uppercase tracking-widest block mb-1.5\">Status</label> <select id=\"active\" name=\"active\" class=\"w-full bg-surface-container-low border-none rounded-lg text-sm font-medium py-2.5 focus:ring-2 focus:ring-primary-container/20\" hx-get=\"/dispatch/trips\" hx-trigger=\"change\" hx-target=\"#trip-table\" hx-include=\".filter-section [name]\" hx-push-url=\"true\" style=\"font-family: 'Inter', sans-serif;\"><option value=\"\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if filter.Active == "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">All</option> <option value=\"active\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if filter.Active == "active" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, ">Active</option> <option value=\"inactive\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if filter.Active == "inactive" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">Inactive</option></select></div><div class=\"min-w-[160px]\"><label for=\"date_from\" class=\"text-[10px] font-bold text-outline uppercase tracking-widest block mb-1.5\">From Date</label> <input type=\"date\" id=\"date_from\" name=\"date_from\" class=\"w-full bg-surface-container-low border-none rounded-lg text-sm font-medium py-2.5 focus:ring-2 focus:ring-primary-container/20\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(filter.DateFrom)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/trips/list.templ`, Line: 73, Col: 29}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" hx-get=\"/dispatch/trips\" hx-trigger=\"change\" hx-target=\"#trip-table\" hx-include=\".filter-section [name]\" hx-push-url=\"true\"></div><div class=\"min-w-[160px]\"><label for=\"date_to\" class=\"text-[10px] font-bold text-outline uppercase tracking-widest block mb-1.5\">To Date</label> <input type=\"date\" id=\"date_to\" name=\"date_to\" class=\"w-full bg-surface-container-low border-none rounded-lg text-sm font-medium py-2.5 focus:ring-2 focus:ring-primary-container/20\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(filter.DateTo)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/trips/list.templ`, Line: 86, Col: 27}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" hx-get=\"/dispatch/trips\" hx-trigger=\"change\" hx-target=\"#trip-table\" hx-include=\".filter-section [name]\" hx-push-url=\"true\"></div><input type=\"hidden\" name=\"sort_by\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(filter.SortBy)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/trips/list.templ`, Line: 94, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\"> <input type=\"hidden\" name=\"sort_dir\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(filter.SortDir)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/trips/list.templ`, Line: 95, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\"></div></div><!-- Trips Table --> <div id=\"trip-table\" class=\"filter-section\" hx-get=\"/dispatch/trips\" hx-trigger=\"every 10s [document.visibilityState==='visible']\" hx-include=\".filter-section [name]\" hx-swap=\"innerHTML\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Table(result, filter).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout(pg, "Trips / Loads").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
