/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: "class",
	content: [
		"./internal/handler/components/**/*.templ",
		// Chart components build class strings in Go, so scan Go sources too.
		"./internal/handler/components/**/*.go",
		// Handlers emit raw HTML fragments (e.g. landing contact thank-you).
		"./internal/handler/*.go",
	],
	theme: {
		extend: {
			colors: {
				"primary": "#000000",
				"on-primary": "#ffffff",
				"primary-container": "#00174b",
				"on-primary-container": "#497cff",
				"secondary": "#515f74",
				"on-secondary": "#ffffff",
				"secondary-container": "#d5e3fc",
				"on-secondary-container": "#57657a",
				"tertiary": "#000000",
				"on-tertiary": "#ffffff",
				"tertiary-container": "#002113",
				"on-tertiary-container": "#009668",
				"tertiary-fixed": "#6ffbbe",
				"tertiary-fixed-dim": "#4edea3",
				"on-tertiary-fixed": "#002113",
				"error": "#ba1a1a",
				"on-error": "#ffffff",
				"error-container": "#ffdad6",
				"on-error-container": "#93000a",
				"background": "#f7f9fb",
				"on-background": "#191c1e",
				"surface": "#f7f9fb",
				"on-surface": "#191c1e",
				"surface-variant": "#e0e3e5",
				"on-surface-variant": "#45464d",
				"surface-dim": "#d8dadc",
				"surface-bright": "#f7f9fb",
				"surface-container-lowest": "#ffffff",
				"surface-container-low": "#f2f4f6",
				"surface-container": "#eceef0",
				"surface-container-high": "#e6e8ea",
				"surface-container-highest": "#e0e3e5",
				"outline": "#76777d",
				"outline-variant": "#c6c6cd",
				"inverse-surface": "#2d3133",
				"inverse-on-surface": "#eff1f3",
				"inverse-primary": "#b4c5ff",
				"primary-fixed": "#dbe1ff",
				"primary-fixed-dim": "#b4c5ff",
				"on-primary-fixed": "#00174b",
				"on-primary-fixed-variant": "#003ea8",
				"secondary-fixed": "#d5e3fc",
				"secondary-fixed-dim": "#b9c7df",
				"on-secondary-fixed": "#0d1c2e",
				"on-secondary-fixed-variant": "#3a485b",
				"on-tertiary-fixed-variant": "#005236",
				"surface-tint": "#0053db",
			},
			fontFamily: {
				"headline": ["Manrope", "sans-serif"],
				"body": ["Inter", "sans-serif"],
				"label": ["Inter", "sans-serif"],
			},
			borderRadius: {
				"DEFAULT": "0.125rem",
				"lg": "0.25rem",
				"xl": "0.5rem",
				"full": "0.75rem",
			},
		},
	},
	plugins: [
		// class strategy: no global [type=text]/select base reset, so app.css
		// form-control styling keeps the cascade it expects.
		require("@tailwindcss/forms")({ strategy: "class" }),
		require("@tailwindcss/container-queries"),
	],
};
