-- +goose Up
-- Core entities
ALTER TABLE customers ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE employees ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE trucks ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE zones ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE zone_pricing ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

-- Dispatch
ALTER TABLE orders ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE order_vehicles ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE order_charges ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE vehicle_damage ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE vehicle_notes ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE trips ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE load_details ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE trip_fuel ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE trip_expenses ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE trip_routes ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

-- Accounting
ALTER TABLE invoices ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE invoice_details ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE payments ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE payment_details ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE credit_memos ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE damage_claims ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE accounts_payable ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

-- Lookups
ALTER TABLE items ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE tax_codes ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE terms ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE dispatch_codes ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE equipment_types ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE regions ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE damage_areas ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE damage_types ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE damage_severities ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE hold_codes ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE declination_codes ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

-- Other
ALTER TABLE attachments ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE loadboard_listings ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE loadboard_claims ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

-- +goose Down
ALTER TABLE customers DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE employees DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE trucks DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE zones DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE zone_pricing DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE orders DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE order_vehicles DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE order_charges DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE vehicle_damage DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE vehicle_notes DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE trips DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE load_details DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE trip_fuel DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE trip_expenses DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE trip_routes DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE invoices DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE invoice_details DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE payments DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE payment_details DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE credit_memos DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE damage_claims DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE accounts_payable DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE items DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE tax_codes DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE terms DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE dispatch_codes DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE equipment_types DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE regions DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE damage_areas DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE damage_types DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE damage_severities DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE hold_codes DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE declination_codes DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE attachments DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE loadboard_listings DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE loadboard_claims DROP COLUMN IF EXISTS deleted_at;
