-- +goose Up
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS posted_by VARCHAR(50);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS posted_by VARCHAR(50);

-- +goose Down
ALTER TABLE invoices DROP COLUMN IF EXISTS posted_at;
ALTER TABLE invoices DROP COLUMN IF EXISTS posted_by;
ALTER TABLE payments DROP COLUMN IF EXISTS posted_at;
ALTER TABLE payments DROP COLUMN IF EXISTS posted_by;
