// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// NotFoundPage renders a branded 404 for authenticated users inside the app
// layout (nav intact), with links back to the Dashboard and Orders.
func NotFoundPage(pg PageContext) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"display:flex; flex-direction:column; align-items:center; justify-content:center; min-height:50vh; text-align:center; padding:2rem;\"><div style=\"max-width:480px;\"><div style=\"font-family:var(--font-heading); font-size:4rem; font-weight:800; letter-spacing:-0.04em; color:var(--primary-container); line-height:1;\">404</div><div style=\"height:4px; width:48px; background:#6ffbbe; margin:1rem auto 1.5rem; border-radius:2px;\"></div><h2 style=\"margin-bottom:0.5rem;\">Page not found</h2><p style=\"color:var(--gray-500); margin-bottom:1.5rem;\">We couldn't find the page you were looking for. It may have been moved, or the link may be incorrect.</p><div class=\"btn-group\" style=\"justify-content:center;\"><a href=\"/\" class=\"btn btn-primary\">Back to Dashboard</a> <a href=\"/dispatch/orders\" class=\"btn\">Go to Orders</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(pg, "Page Not Found - "+pg.Brand.Name).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// NotFoundFragment renders a minimal 404 message for HTMX/partial requests,
// so a swapped-in target doesn't get a full HTML document.
func NotFoundFragment() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div style=\"text-align:center; padding:2rem; color:var(--gray-500);\"><h3 style=\"margin-bottom:0.25rem;\">Page not found</h3><p>The requested resource could not be found. <a href=\"/\">Return to the dashboard</a>.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// NotFoundPublic renders a minimal branded 404 for unauthenticated requests,
// matching the login-page aesthetic (navy #00174b + mint #6ffbbe accent).
func NotFoundPublic(brand Brand) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Page Not Found - ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(brand.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/notfound.templ`, Line: 41, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</title><link rel=\"icon\" type=\"image/svg+xml\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 templ.SafeURL
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinURLErrs(brand.FaviconFile)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/notfound.templ`, Line: 42, Col: 65}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Manrope:wght@700;800&display=swap\"><link rel=\"stylesheet\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 templ.SafeURL
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinURLErrs(AssetVersion("/static/css/app.css"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/notfound.templ`, Line: 46, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"><style>\n\t\t\t\t.nf-wrap {\n\t\t\t\t\tmin-height: 100vh; display: flex; align-items: center; justify-content: center;\n\t\t\t\t\tpadding: 24px;\n\t\t\t\t\tbackground-color: #00174b;\n\t\t\t\t\tbackground-image:\n\t\t\t\t\t\tradial-gradient(at 0% 0%, rgba(0,83,219,0.15) 0px, transparent 50%),\n\t\t\t\t\t\tradial-gradient(at 100% 100%, rgba(111,251,190,0.1) 0px, transparent 50%);\n\t\t\t\t}\n\t\t\t\t.nf-card {\n\t\t\t\t\twidth: 100%; max-width: 440px; text-align: center;\n\t\t\t\t}\n\t\t\t\t.nf-brand {\n\t\t\t\t\tfont-family: var(--font-heading); font-weight: 800; font-size: 28px;\n\t\t\t\t\tletter-spacing: -0.04em; color: white; margin-bottom: 8px;\n\t\t\t\t}\n\t\t\t\t.nf-accent { height: 4px; width: 48px; background: #6ffbbe; margin: 0 auto 40px; border-radius: 2px; }\n\t\t\t\t.nf-code {\n\t\t\t\t\tfont-family: var(--font-heading); font-weight: 800; font-size: 72px;\n\t\t\t\t\tletter-spacing: -0.04em; color: white; line-height: 1; margin: 0;\n\t\t\t\t}\n\t\t\t\t.nf-title {\n\t\t\t\t\tfont-family: var(--font-heading); font-size: 24px; font-weight: 700;\n\t\t\t\t\tcolor: white; margin: 16px 0 12px;\n\t\t\t\t}\n\t\t\t\t.nf-text { color: #b4c5ff; font-size: 15px; font-weight: 500; line-height: 1.6; margin: 0 0 32px; }\n\t\t\t\t.nf-link {\n\t\t\t\t\tdisplay: inline-flex; align-items: center; gap: 8px;\n\t\t\t\t\tpadding: 14px 28px; background: #6ffbbe; color: #00174b;\n\t\t\t\t\tborder-radius: 12px; font-size: 13px; font-weight: 700;\n\t\t\t\t\ttext-transform: uppercase; letter-spacing: 0.02em; text-decoration: none;\n\t\t\t\t\ttransition: opacity 0.15s;\n\t\t\t\t}\n\t\t\t\t.nf-link:hover { opacity: 0.9; }\n\t\t\t</style></head><body><div class=\"nf-wrap\"><div class=\"nf-card\"><div class=\"nf-brand\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(brand.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/handler/components/notfound.templ`, Line: 86, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"nf-accent\"></div><p class=\"nf-code\">404</p><h1 class=\"nf-title\">Page not found</h1><p class=\"nf-text\">The page you're looking for doesn't exist or you may need to sign in to view it.</p><a href=\"/login\" class=\"nf-link\">Go to Sign In</a></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
